name: 'OMFG - Oh My Forking Git'
description: 'Sync your forked repository with upstream including code, workflows, and secrets'
author: 'GooseyPrime'
branding:
  icon: 'git-branch'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token with appropriate permissions'
    required: true
    default: ${{ github.token }}
  
  upstream-repo:
    description: 'Upstream repository (owner/repo format)'
    required: false
    
  dry-run:
    description: 'Run in dry-run mode to preview changes without applying them'
    required: false
    default: 'false'
    
  sync-code:
    description: 'Sync code changes from upstream'
    required: false
    default: 'true'
    
  sync-workflows:
    description: 'Sync GitHub Actions workflows from upstream'
    required: false
    default: 'true'
    
  sync-secrets:
    description: 'Sync repository secrets from upstream (requires admin access)'
    required: false
    default: 'false'
    
  conflict-strategy:
    description: 'Strategy for handling conflicts: merge, rebase, or fail'
    required: false
    default: 'merge'
    
  include-patterns:
    description: 'Comma-separated list of file patterns to include (glob patterns)'
    required: false
    default: '*'
    
  exclude-patterns:
    description: 'Comma-separated list of file patterns to exclude (glob patterns)'
    required: false
    default: ''
    
  require-approval:
    description: 'Require manual approval before applying changes'
    required: false
    default: 'false'

outputs:
  changes-summary:
    description: 'Summary of changes that were or would be applied'
    
  sync-status:
    description: 'Status of the sync operation (success, conflicts, failed)'
    
  conflicts-detected:
    description: 'List of files with conflicts'
    
  files-changed:
    description: 'Number of files changed'

runs:
  using: 'node20'
  main: 'dist/index.js'