name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint code
      run: npm run lint
      
    - name: Run tests
      run: npm test
      
    - name: Build action
      run: npm run build
      
    - name: Check for uncommitted changes
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "Uncommitted changes detected:"
          git status --porcelain
          exit 1
        fi

  integration-test:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test action (dry-run)
      uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        dry-run: true
        sync-code: true
        sync-workflows: false
        sync-secrets: false