# Example workflow file for users to copy to their forked repositories
# Save this as .github/workflows/sync-fork.yml in your forked repository

name: Sync Fork with Upstream

on:
  # Run daily at 6 AM UTC
  schedule:
    - cron: '0 6 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run in dry-run mode (preview changes only)'
        required: false
        default: false
        type: boolean

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch full history for proper sync
          fetch-depth: 0
          
      - name: Sync with upstream
        id: sync
        uses: GooseyPrime/OMFG@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: ${{ github.event.inputs.dry-run || false }}
          # Uncomment and customize these options as needed:
          # upstream-repo: 'original-owner/repo-name'  # Auto-detected if not specified
          # sync-code: true
          # sync-workflows: true
          # sync-secrets: false
          # conflict-strategy: 'merge'  # merge, rebase, or fail
          # include-patterns: 'src/**,docs/**'
          # exclude-patterns: 'tests/**,*.tmp'
          # require-approval: false
          
      - name: Display sync summary
        run: |
          echo "## Sync Summary" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ${{ steps.sync.outputs.sync-status }}" >> $GITHUB_STEP_SUMMARY
          echo "**Files Changed:** ${{ steps.sync.outputs.files-changed }}" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.sync.outputs.conflicts-detected }}" != "" ]; then
            echo "**Conflicts:** ${{ steps.sync.outputs.conflicts-detected }}" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Changes:**" >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.sync.outputs.changes-summary }}' >> $GITHUB_STEP_SUMMARY
          
      - name: Create issue on conflicts
        if: steps.sync.outputs.sync-status == 'conflicts'
        uses: actions/github-script@v7
        with:
          script: |
            const conflicts = '${{ steps.sync.outputs.conflicts-detected }}';
            const issueTitle = `🔄 Fork sync conflicts detected - ${new Date().toISOString().split('T')[0]}`;
            const issueBody = `## Sync Conflicts Detected
            
            The automated fork sync encountered conflicts that need manual resolution.
            
            **Conflicted Files:**
            ${conflicts.split(',').map(file => `- ${file.trim()}`).join('\n')}
            
            **Next Steps:**
            1. Pull the latest changes locally
            2. Resolve the conflicts manually
            3. Push the resolved changes
            
            **Sync Summary:**
            \`\`\`
            ${{ steps.sync.outputs.changes-summary }}
            \`\`\`
            
            ---
            *Generated by OMFG (Oh My Forking Git) Action*`;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['sync-conflict', 'automated']
            });